version: '3.3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx/html
  adminer:  # Corrected indentation
    image: adminer
    hostname: 34.207.211.150
    restart: always
    ports:
      - 8070:8070
