version: '3.3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx/html
  adminer:  # Corrected indentation
    image: adminer
  adminer:
    image: adminer
    ports:
      - "8070:8080"
    environment:
      ADMINER_DESIGN: nette
    hostname: 34.207.211.150
